### ISSUE TITLE
TFAR not functioning correctly.

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#11]
Jerkin to fix radios

Suggest that check version used in development versus version used on server. That might be a small issue that can be rectified easily by switching to new version.

**Comment by jerkinmerkin** [comment]
Identified the issue.  Vehicle radios are bluefor, backpack radios are indfor, and rifleman radios are opfor.  I always seem to do this.  Will change radios around so that they're all on one side.  Does anyone know if you can just turn side encryption off?

**Comment by FoxKilo** [comment]
Reference most of this thread regarding alternative ways to setup and control TFAR. Ref old issue of assigning presets. Don't see no encryption option though.

https://forums.bistudio.com/topic/159393-task-force-arrowhead-radio/page-159#entry2856256

**Comment by jerkinmerkin** [comment]
Fixed on my end.  Needs testing

**Comment by jerkinmerkin** [comment]
According to Kingheavy everything works now.  Closing.

**Comment by coachwn** [comment]
TFAR not working correctly with short range radios on all teams in the server. Each group is able to connect via long range radios.

**Comment by FoxKilo** [comment]
Needs further testing but SOF <> TACP short range is fine, can't hear any long range. TACP > Rest of the world no short range trans but long range is working fine. Will flesh this out tomorrow when I get home for super full analysis.

**Comment by jerkinmerkin** [comment]
This was working before no?

**Comment by jerkinmerkin** [comment]
What radios do they have?

**Comment by coachwn** [comment]
The backpack radio R-169-5KNE is the culprit in my opinion; I can not hear anything on it when it is the only radio I have on my character.

**Comment by coachwn** [comment]
Radios in play for all command level/TACP elements are the 152 personal radio and the R-168-5KNE backpack

**Comment by Hauser1** [comment]
Playing yesterday we had a TACP, an SF member, and armor member, and a command staff member with no backpack radio.  The TACP and the SF could talk to each other on short range, but the command staff and armor guy could not hear them.  The TACP could use his backpack radio and be heard by the armor and command people on their short ranges.  All the radios had designation numbers after them in the inventories, like AN/PRC-152 9, or AN/PRC-152 8.

**Comment by jerkinmerkin** [comment]
It's not the backback radios, they've been in every one of my deployments and worked fine.  Will double check the side radios to make sure I didn't include numbers in them

**Comment by jerkinmerkin** [comment]
Or am I supposed to include the same number in them?  Hmmm will check my old missions...

**Comment by jerkinmerkin** [comment]
Nope, none of the side radios have numbers attached to them... IDK why TFAR is assigning number them, and thats how its works in all my previous missions.  This is weird.  I guess ill try assigning the same numbers to them and see what happens.

**Comment by jerkinmerkin** [comment]
Turns out I broke it.  Fixed now.
