### ISSUE TITLE
Write OPORD and replace it in briefing.sqf

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/Queens-Stallions#16]
Need to get off my ass and do it.

**Comment by coachwn** [comment]
Hauser can write pretty good from what I have heard...just look at his GA Hauser novel collection.

**Comment by Hauser1** [comment]
Do you want me to write it, I would be more than happy to after you brief me.

**Comment by jerkinmerkin** [comment]
Appreciate the offer, but I started it last night.  Wont take long, just got caught up fixing persistence.

**Comment by jerkinmerkin** [comment]
Working on this right now, will get this put in the briefing.sqm for the release version and then we are good to go.

**Comment by jerkinmerkin** [comment]
OPORD finished.  See here.

[https://docs.google.com/document/d/1EVX_GxnKU-qk9TuL46rKCOT2o6c115VR70zRq4DCifg/edit?usp=sharing](url)

The only thing I was unsure of is the radio channel for Spearhead HQ, I would rather have it be the same from the last deployment but I couldn't find the OPORD.  Its open to editing so if someone remembers they can edit it for me.  Nichols, you can go ahead and use this on the forums.  Leave the issue open as I still haven't but it in the mission briefing.  That's a pretty painstaking task which will probably come later this weekend.

**Comment by FoxKilo** [comment]
Seems pretty straight forward to me, I like it, detailed enough without any waffle.

In answer to your question I would swap HQ and fires net around considering 40.2 has been fires net since forever. Previous OPORD had no HQ net as usually they stick together and use Task Force

**Comment by coachwn** [comment]
Frequencies: 
 
Channel 1 - 036.6 - Task Force Net
Channel 2 - 037.7 - Aviation Net
Channel 3 - 040.2 - Fires Net
Channel 4 - 042.6 - RFR Net
Channel 5 - 047.3 - RCR Net
Channel 6 - 051.8 - CIA Net
Channel 7 - 058.4 - MEDEVAC/CASEVAC Net
Channel 8 - 062.8 - CSAR/SERE Net

**Comment by coachwn** [comment]
Frequencies: 
 
Channel 1 - 036.6 - Task Force Net
Channel 2 - 037.7 - Aviation Net
Channel 3 - 040.2 - Fires Net
Channel 4 - 042.6 - RFR Net
Channel 5 - 047.3 - RCR Net
Channel 6 - 051.8 - CIA Net
Channel 7 - 058.4 - MEDEVAC/CASEVAC Net
Channel 8 - 062.8 - CSAR/SERE Net

**Comment by coachwn** [comment]
https://spearheadgaming.net/index.php?/topic/3748-operation-queens-stallions-op-order/

**Comment by FoxKilo** [comment]
You posted that with the copied version from Isla duala as above. Need to change the names!
