### ISSUE TITLE
Add bi-signs for server-side and optional mods.

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/Queens-Stallions#18]
Need for:
 JSRS4 APEX
Blastcore
Ace Tracers
Advanced Sling Load
Advanced Rappelling
Advanced Towing

**Comment by jerkinmerkin** [comment]
Please list any other I've forgotten.

**Comment by coachwn** [comment]
ace_tracers is already on the server side. We can move the sling load, rappelling and towing to server side also they just need to be called in the init or description.

**Comment by jerkinmerkin** [comment]
advanced slingload added to mission folder.

**Comment by FoxKilo** [comment]
Implementation done.
