### ISSUE TITLE
SPG-9 UAZ

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#2]
SPG-9 UAZ is bugged, replicable issue of rounds hitting an invisible barrier 50m from the truck. This happens after 50% of the 12 rockets are expended. To clarify you and the enemy can fire 6 rounds from the SPG-9 gun truck and experience no problems, firing the remaining 6 rockets results in each rocket hitting a barrier approx 50m in a 360 degree radius. Occupants are safe from shrapnel except for HE rounds.

If you reload the truck to only 50%, this negates the effect.

Work-around: Load the SPG9's in EMPTY and have users load up before missions. No solution for AI vehicles which experience the same problem.

**Comment by FoxKilo** [comment]
When reloading, ACE will rearm 2 missiles per reload however this doesn't show up in the ammo count. When firing you'll first expend the non-counted rounds which exist in the truck and have a fast reload. When you've expended the non-counted rounds you'll see the ammo counter tick down normally and reload times return to normal. Overall a buggy weapon system for the vehicle. If there is another in the modpack we can use then i'd say switch it out.

**Comment by FoxKilo** [comment]
50m wall seems to work when any combination of counted/non-counted missile that is 6 or greater is met.

**Comment by jerkinmerkin** [comment]
I can try using CUP UAZs instead of RHS ones.

**Comment by FoxKilo** [comment]
Currently testing in virtual arsenal

**Comment by FoxKilo** [comment]
CUP ones work but have a very strong overpressure issue towards the front 180 degrees of the truck. Need atleast 75m radius away from the truck while firing. Deadly as shit.

**Comment by coachwn** [comment]
So the question I have is if the RHS one's work once the ammo load is adjusted why are we looking at alternatives?

**Comment by jerkinmerkin** [comment]
Switched to CUP UAZs.
