### ISSUE TITLE
Server settings

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#24]
Set to;

Stance Indicator: Faded
Weapon Info: Faded

**Comment by coachwn** [comment]
Should already be done server side. Will check again but TADST should be done correctly. I also noticed that some were having HUD issues yesterday which may or may not be related since I have not had those problems at all.

**Comment by jerkinmerkin** [comment]
Fade seemed to work fine for me.

**Comment by coachwn** [comment]
ARES-ACHILLES not allowing load into the game.

**Comment by coachwn** [comment]
Has anyone still had these issues? I haven't seen it yet.
