### ISSUE TITLE
R3F Logistics Not Working correctly

### ISSUE THREAD

**Issue by Hauser1** [Spearhead-Gaming-Milsim/Queens-Stallions#25]
Received an error when attempting to access large connex inventory and was unable to access it.  Did not get a screengrab of the error.  Also did not work for Williams

**Comment by coachwn** [comment]
Checking the mission file and I do not see anything out of place with how it should or should not function. Will upload new mission file later and see if that makes a difference.

**Comment by jerkinmerkin** [comment]
The connex boxes are a copy paste of what worked in my last two missions.  I'm using the old version of R3F, so could the old version be broken and unusable now?

**Comment by coachwn** [comment]
Will have to check and see if R3F updated that stuff lately. I don't think they did but I could be wrong.

**Comment by FoxKilo** [comment]
Is there supposed to be R3F code in the init lines of things we want to use? If so there are objects missing this code.

**Comment by jerkinmerkin** [comment]
In the connex boxes yes.

**Comment by coachwn** [comment]
Can confirm that the boxes labeled SP1, SP2 & SP3 have no init lines in editor.

**Comment by jerkinmerkin** [comment]
Lol must have forgotten to put the code in he init.  That's okay, a quick copy paste will fix that.

**Comment by FoxKilo** [comment]
If R3F is supposed to work in vehicles too, pretty sure King said it wasn't working for the vics either.

**Comment by jerkinmerkin** [comment]
Which Vic's specifically?

**Comment by FoxKilo** [comment]
I'm on the server now applying the TFAR fix. I'll get a list for you

**Comment by FoxKilo** [comment]
Considering that I can't get into the vehicle inventory of any of SOF's vics i'm going to just say that no vehicles have R3F inventory working.

**Comment by coachwn** [comment]
ACE for wheels and treads so non-issue.

**Comment by coachwn** [comment]
Something with R3F is creating an issue with saving the mission file and it loading back in correctly. I have updated the title here to reflect the current issue. Also it seems that may have something to do with the War Room not reporting correctly also.

**Comment by jerkinmerkin** [comment]
ALiVE_SYS_LOGISTICS is definitely the culprit.  I've removed it, and now both R3F works and vehicles are persisting.

**Comment by jerkinmerkin** [comment]
Yup, and i put it back and now they dont work again.  So we'll definitely have to go without saving logistic items.

**Comment by coachwn** [comment]
Ok so let's get a report back to ALIVE and R3F with our findings along with the mission file and mod list so they can work on a fix.

**Comment by jerkinmerkin** [comment]
Let's test it with the vanilla mission before we report anything to ALiVE

**Comment by jerkinmerkin** [comment]
So, R3F works now.  I tested persisting some hescos and the hescos did persist its location however the thing rotated itself.  I've asked some guys on the server to build a FOB and then I'll try persisting that.  I'm gonna call this one closed tho, since we know it 95% works.

**Comment by coachwn** [comment]
OK did a complete save and then closed the server and restarted from the mission save. Guess what happened???? Everything was back at original start positions. No hesco areas and no base up by Pobeda Dam...everything fresh but player saves.

**Comment by jerkinmerkin** [comment]
Vic's too?

**Comment by coachwn** [comment]
Yep

**Comment by jerkinmerkin** [comment]
WTF...

**Comment by coachwn** [comment]
I wish I knew...I am going to test it again since I made sure the custom settings were ready for the server and that was the only tweak I made to the restart but that should have had ZERO effect on the mission file internally.

**Comment by jerkinmerkin** [comment]
yea, can confirm.  vehicle persistence is 100% not working again.

**Comment by jerkinmerkin** [comment]
So it's saving players and enemies, just not vehicles again.

**Comment by jerkinmerkin** [comment]
Fuck it, when I get home I'm remove R3F completely.

**Comment by coachwn** [comment]
Roger that...will leave V9 running till later today.

**Comment by jerkinmerkin** [comment]
Go ahead any play around with v10 today, we'll make a v11 for release

**Comment by coachwn** [comment]
OK

**Comment by coachwn** [comment]
Mission seems to work good. Haven't saved yet since v10 still has R3F.

**Comment by jerkinmerkin** [comment]
Go ahead and save it.  Some thing are changed in v10.

**Comment by coachwn** [comment]
Tried saving V10 after the AI and players fought over the base...lots of stuff spread around the area near cav spawn and the hangar was destroyed...short version is the base reloaded back to initial start location for all vehicles and player spawns were as we have begun to expect along with AI spawning back in their location near cav spawn. R3F still broke...

**Comment by jerkinmerkin** [comment]
Testing has shown it's not R3F that's breaking persistence.
