### ISSUE TITLE
Ace error Possibly caused by updating repo

### ISSUE THREAD

**Issue by Jmaster9999** [Spearhead-Gaming-Milsim/Queens-Stallions#26]
Aviation units are unable to use the ace interaction menu, ace medical or ace options menu. This is a critical bug as pilots are not able to change view distance and the view distance is locked at 800m.

**Comment by jerkinmerkin** [comment]
Everyone in aviation is having this issue?

**Comment by Jmaster9999** [comment]
from what I can tell, both me and berwick had the issue. Although I believe it could be an issue with user configs. I'm testing that now

**Comment by coachwn** [comment]
Gotta be a user side situation as that was not a problem earlier in the week. I was flying and able to adjust on the fly...I think it is related to the whole missing HUD thing you guys mentioned earlier as well.

**Comment by Jmaster9999** [comment]
Nope, Not a user side Issue as far as I can tell, just reinstalled ace and the issue still persists

**Comment by jerkinmerkin** [comment]
Most likely a client side issue, as a screwed up ace setting would affect everybody, not just pilots.

**Comment by Jmaster9999** [comment]
hmmm, have some people try out the pilot slots to check just in case. I'll investigate a bit more on my client.

**Comment by Jmaster9999** [comment]
Appears to be a clientside issue. I'm changing the issue title to reflect this.,

**Comment by FoxKilo** [comment]
Da....some pilots are fine, others are not. Modset issue client side only.

**Comment by coachwn** [comment]
pilots are whiners...therefore it doesn't matter what they think. Just like SF guys.....:D

**Comment by jerkinmerkin** [comment]
This is true.

**Comment by jerkinmerkin** [comment]
I'd try deleting and redownloading @SH_CDF

**Comment by coachwn** [comment]
closing this issue.
