### ISSUE TITLE
Check ammo loads for all vehicles for Armor and Cav

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#27]
They are reporting that they have boxes of NATO ammo instead of ammo for Russian weapons. Need to check that and fix before going live.

**Comment by jerkinmerkin** [comment]
Are we talking in the vehicles?

**Comment by coachwn** [comment]
Yes

**Comment by FoxKilo** [comment]
NATO M80 belts for the M240 machine gun are in the majority of cav vehicles, along with the NATO M18 smoke grenades being present in all ground vics from what I can see. That is the limit of this issue.

**Comment by jerkinmerkin** [comment]
only thing I've found out of place is the 100rnd belts.  It's not really hurting anything.  Is it worth pushing a repo update to remove them or should we just leave them in and ignore them?

**Comment by KingHeavy** [comment]
I can get my guys to pull them out replace them with ok belts and save the vice that way. It all works for me.

**Comment by jerkinmerkin** [comment]
Sounds good, closed.
