### ISSUE TITLE
Framerate bug that effects some players and doesn't effect others

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#28]
Some players report not getting game killing framerates but others are getting effects with frame rates dropping down into 1-4fps and eventually crashing ARMA. I think it is a BI bug that has been introduced into Chernarus since the last update to Arma but can't confirm yet.

**Comment by jerkinmerkin** [comment]
Pretty sure the latest update introduced another memory leak.  This mission ran fine before 1.66 and now my frames are fucked too

**Comment by coachwn** [comment]
I think this one is related to the OPCOM report. Going to close it out unless we can confirm it is separate from the others.
