### ISSUE TITLE
Black screen of death- intermittent issue

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#29]
Some users, especially high end users are getting black screens after a period of gaming. Did some research and the likely cause is overloading of textures within the AGP.

One fix is to try to run with -nobenchmark.

Other topical fix is to bring up the console by pressing Left Shift + Num (-) and giving the command "flush". "Flush all video memory to cure performance issue caused by textures being placed in the AGP "

Had this happen 3 times to myself, Spanky and some other guys however have not had a chance to try this fix.

**Comment by coachwn** [comment]
Going to check for conflict with ASR_AI and VCOM possibly causing overloads in the background on the server. There were some reports of that happening from what I have researched but nothing game breaking. Will dig into this with Genesis92X as well.

**Comment by FoxKilo** [comment]
Issue seems to be with people running DX11 reference my RPT.

http://pastebin.com/Sn8LnVCg

**Comment by coachwn** [comment]
I wonder if it is related to the terrain?

**Comment by FoxKilo** [comment]
Again it's possible, but it may be a culmination of multiple things that lead up to this one event where loading a texture causes a spike in memory usage and causes DX11 to crash with the outofmemory error as seen. My card has 8GB of GDDR5 memory backed up by 16GB of DDR3 RAM so it's not like i'm punching above my weight.

**Comment by coachwn** [comment]
Same here...on the specs.

**Comment by FoxKilo** [comment]
Yet you haven't had the issue, Spanky has a better rig than us and he's had the same problem. I was going to suggest connection issues to the server as that could bottleneck things but my ping was 83 and bandwidth around +-400...which is better than some 'muricans were getting yesterday when I checked.

**Comment by coachwn** [comment]
Yeah let's monitor this but still keep the issue open.

**Comment by coachwn** [comment]
I wonder if this issue linked here has something to do with the server performance being pushed onto the client side.

https://github.com/ALiVEOS/ALiVE.OS/issues/156#issuecomment-266749407

**Comment by coachwn** [comment]
Thinking it is a BI code problem that was introduced with 1.66. Unable to reproduce on my end but do have serious frame rate issue when objectives and objects gets too high. Have changed my view settings to reduce the amount of stuff being pushed through by a significan't amount and still have small microstutters.

**Comment by FoxKilo** [comment]
As recently as yesterday afternoon other groups have been filing complaints to BI about this exact issue, describing the same parameters and diagnostic results. Almost comes naturally now to expect memory problems with each update...
