### ISSUE TITLE
No TF HQ slots

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#3]
No HQ slots so Nichols, Lee, Hauser and Huzz are banned from playing the mission. Also query slot names, seems like King etc have been named as PSGs.

**Comment by coachwn** [comment]
Huzz hasn't played or logged into ALiVE in at least 8 months to my knowledge so that part is of no consequence.

**Comment by FoxKilo** [comment]
aye, just commenting that there are no HQ slots considering this was made for SLF/SRF structure. Minor adjustments to switch over to the current structure we have.

**Comment by FoxKilo** [comment]
Just going to leave this suggestion here, except swap out the man bag for the pistol holster and mapcase (vests)
http://puu.sh/sGiWg/85595e6f1f.jpg

**Comment by coachwn** [comment]
Nice suggestion...now we need to get this sorted out and Jerkin doesn't have a lot of time so any help on this would be appreciated with Jerkins blessing of course.

**Comment by coachwn** [comment]
Jerkin fixing while working on missing uniform bug.
