### ISSUE TITLE
TFAR Module

### ISSUE THREAD

**Issue by FordJMspearhead** [Spearhead-Gaming-Milsim/Queens-Stallions#30]
TFAR needs to be fully implemented, it is not dragging people and some people trans over global

**Comment by jerkinmerkin** [comment]
Nichols, the TS should be named. Bastion of ALiVE - OP Queen's Stallions

**Comment by jerkinmerkin** [comment]
And change pw to 123

**Comment by FoxKilo** [comment]
only a JC or above can change the channel. Sad face.

**Comment by FoxKilo** [comment]
Fix implemented. Issue closed.

**Comment by coachwn** [comment]
TFAR was not dragging anyone in yesterday when we started it. It was named correctly with 123 as the pw for the channel. That is why it was opened so we could get people into the channel and out of the others.

**Comment by FoxKilo** [comment]
So just to reference for future generations, the differences in naming was as follows;

Bastion of ALiVE - Queens Stallion

TO

Bastion of ALiVE - OP Queen's Stallions

*removed channel password for optimal OPSEC*

**Comment by coachwn** [comment]
Closed again in order to keep other TFAR issue moving forward. [https://github.com/Spearhead-Gaming-Milsim/Queens-Stallions/issues/11](url)
