### ISSUE TITLE
OPCOM instances super high

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#31]
Just loaded into the mission and loaded on my box after removing the ALiVE Data module. The message from ALiVE is as follows:

"There are 278 objectives for this ["ChDKZ_Opfor'] OPCOM instance! Please lower the objective count for performance reasons, suggested is below 80!"

I think this might have a few reasons to be for the save time taking so long as well as the tremendous frame rate drops that people have been experiencing.

**Comment by coachwn** [comment]
Ran it on the local box and it crashed the game with a "Status Application Hang" error message.

**Comment by jerkinmerkin** [comment]
We can try lowering it and see what happens.  Worth testing at the very least.  It's never been an issue before tho, but perhaps that with the combination of arma updates fucked it.

**Comment by FoxKilo** [comment]
278/3= 93.....split the map up into 3 circular bands or sectors and we'll cordon them off using LOAs.

**Comment by coachwn** [comment]
Need to lower instances of OPCOM somehow and see if that helps; server went through several freezes this afternoon during extra test session and eventually came out of it. It happened once with a fire team of players out near Devils Castle.

**Comment by jerkinmerkin** [comment]
Filter objective priority.  Sorry, won't be able to get on until probably tomorrow

**Comment by jerkinmerkin** [comment]
Filtered and lowered to around 150.  Performance much improved.  Will toy with it some more and see what we can push it to.

**Comment by coachwn** [comment]
Probably the best performing version with the lower objective count; unless we drop back to lower count from what we have in V.7 then we should limit with LOA.
