### ISSUE TITLE
Motorbikes?

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/Queens-Stallions#32]
Why do I see screens of SOF with motorbikes?  I never put them in the mission, although I joked once about putting them in.  They should only have UAZs and GAZs.  Please do not be adding assests the mission maker did not intend to have in the scenario.

**Comment by coachwn** [comment]
Not sure since I was not messing around with units. They are not in the mission file that I put in place that I am aware of.

**Comment by FoxKilo** [comment]
Nothing has been added to the mission that shouldn't be there. That was me doing a proactive experimental test to see if the bikes are still flip at low speeds (confirmed). They also don't have ace compats for them either. Purely fact finding on my part.
