### ISSUE TITLE
Weather Module

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#33]
Using advanced functions from Ares, rain seems to be bugging out as when you put it on it turns on/off once per second. Tried with immediate and smooth transitions with the same results.

Wind also seems to be suffering a similar bug in that if you set any wind it'll initialise what you set it to then reset to normal. Query if something in the mission file is overwriting this ability and consider what weather compositions we want to happen during the deployment.

Real life weather events would be favourable, it's often overlooked.

**Comment by jerkinmerkin** [comment]
Don't mess with the weather, let ace weather do its thing or else it'll screw with ace ballistics.

**Comment by coachwn** [comment]
The bug that we found in the last mission was because of ACE weather and ALiVE weather bugging each other out.

**Comment by jerkinmerkin** [comment]
I'll make sure I don't have both modules down.
