### ISSUE TITLE
Reported that helicopters can not repaired if damaged.

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#34]
Attempting to verify this now on the server. Will keep working on it till later tonight after I bring the server back up.

**Comment by coachwn** [comment]
Pilots possibly unable to repair vehicles because they have no backpacks to load in toolkits and use them.

**Comment by jerkinmerkin** [comment]
Nope, will fix.  In the mean time, don't crash.... bahaha

**Comment by jerkinmerkin** [comment]
Pilots set as engineers, use repair truck to repair.
