### ISSUE TITLE
Vehicle repairs

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#35]
Tracked vehicles requesting backpacks for same reason as the pilots to put repair kits into so they can use them while in the field.

**Comment by jerkinmerkin** [comment]
Meh I'm just not gonna require a repair kit

**Comment by FoxKilo** [comment]
Doesn't need to be fixed in the mission file, can just zeus them in 10 backpacks and let them figure their own logistics routine.

**Comment by coachwn** [comment]
Sounds good then we can persist them by placing in vehicles.

**Comment by KingHeavy** [comment]
Yea. back packs and our own routine is fine with me.

**Comment by jerkinmerkin** [comment]
Removed the need for toolkits.  Can repair in the field without them.

**Comment by jerkinmerkin** [comment]
To be clear, can repair wheels and tracks without them.  You'll need a repair truck for full repairs.
