### ISSUE TITLE
Tremendous desync on server that is noticeable by clients.

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#36]
All clients on server experiencing major game pausing lag that is keeping them in place for 5+ minutes. Version 7 has been up for a little over 3.5 hours before I did a hard reset of the server to the beginning with v.7 file. Going to pull RPT and go through it but something is causing massive lag; it could be the artillery function or it could be the R3F....we just don't know at this time. Needs concerted testing effort to see if this is a game breaking bug and we need to collect rpt files from as many as possible not just server side.

**Comment by coachwn** [comment]
Just been on for about an hour and haven't had a bit of desync yet. Also Arty isn't outrageous as of what I have seen yet.

**Comment by jerkinmerkin** [comment]
Did we have this problem at all on 6.5 or did it just start with 7?

**Comment by coachwn** [comment]
Do not recall as I didn't spend a lot of time with it. It seems like there was some but again I don't recall 100%.

**Comment by coachwn** [comment]
Thought this might at least lead to some ideas about the whole desync and server crash aspect.

http://alivemod.com/forum/2597-dx11-error-createtexture-failed-e-outofmemory/10#p17300

**Comment by jerkinmerkin** [comment]
So I bumped the opcom objectives back  to 250 in v7.  V6.5 only had 150, so if there was no desync on 6.5 but there is on v7 then too many objectives is the culprit.

**Comment by coachwn** [comment]
Yep that is what it sounds like.

**Comment by coachwn** [comment]
Possibly could be due to high objective count but that should be able to be limited via LOA for entire map.
