### ISSUE TITLE
Fix Difficulty settings

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/Queens-Stallions#38]
I broke difficulty settings Nichols :(

I just closed TADST and now it keeps launching in easy mode even though its set to custom.  I probably just  don't know what I'm doing with TADST, please show me what to do so I can fix it in the future.  Sorry!

**Comment by coachwn** [comment]
No problem at all. I will work on it in a little bit and get the steps for fixing back to you.

**Comment by coachwn** [comment]
Done...just need to ensure that if you use TADST that when you select the mission in the check mark of that area that the small drop down is always selected for custom and hit the green check to the right of the drop down menu. That will ensure you are using the custom settings from the difficulty menu.
