### ISSUE TITLE
Persist Vehicles for Release

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/Queens-Stallions#39]
I will have a pre-release version ready to go by tomorrow.  Once its up, we all need to interact with all the vehicles and boxes.  After saving, I'll upload a release version with all the vehicles and boxes deleted from the editor, and then we will be good to go for Saturday!

**Comment by FoxKilo** [comment]
I will be working from home tomorrow (Thursday) so get with me and let's jam.

**Comment by coachwn** [comment]
Yep will be free till around noon central time tomorrow.

**Comment by jerkinmerkin** [comment]
Cool, I'm wedding cake tasting tomorrow so I wont be working either, although I'll be tied up with that until later.

**Comment by jerkinmerkin** [comment]
v10 will be the pre-release version, its on the box whenever you guys can get to it.  OPORD and briefing will be ready for v10 release version after we persist the vics and boxes.
