### ISSUE TITLE
Turn on NVG down sights (custom setting is not on/off)

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#4]
Currently can't use iron sights at night due to how the weapon models work.

**Comment by coachwn** [comment]
Can you elaborate a little more please? It is specific to the weapon model or what?

**Comment by FoxKilo** [comment]
AFAIK it's a global setting so that when you aim down optics, NVGs are turned off to simulate real life where an optic doesn't work with nods. However due to the weapon systems being modelled how they are, iron sights are included with all the AK pattern rifles. Therefore no-one can use nods and fire a weapon at night.

**Comment by jerkinmerkin** [comment]
That will stay.  You should have lasers for your VS Vals and NVG optics you can attach.

**Comment by FoxKilo** [comment]
Only see the GOSHAWK NVG scope in the box currently. In previous missions this was not an issue as NVGs worked with irons but not with optics which is what they are asking for. Don't see lasers for any of our rifles.

**Comment by jerkinmerkin** [comment]
Check AS  Val's as they should have lasers pre-attached.  Will check for NVG optics.  Noble Resolve and Sultan's Wrath both ran with this setting.

**Comment by FoxKilo** [comment]
Need to double check lasers/red dot site compatability but talked with brass and they've agreed to keep it off.
