### ISSUE TITLE
Update repo to latest version of ace

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/Queens-Stallions#40]
Make sure we do this before release.

**Comment by coachwn** [comment]
Updating repo now with latest version of ACE and checking on possible updates for CBA and others as well.

**Comment by coachwn** [comment]
Done

**Comment by coachwn** [comment]
Need to pull all aspects of ACE....NOT ACEX out of @SH_CDF folder. If we add it to that then we will be constantly fighting an update battle since people will have the wrong versions of ACE periodically no matter what we do; If we run with latest version of ACE.

**Comment by coachwn** [comment]
Done again
