### ISSUE TITLE
Create SQM of vehciles and boxes.

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/Queens-Stallions#44]
Since logistics won't persist ATM, but enemies and players do, I am going to create a v13 for the launch version without any vehicles.  I need someone to run an SQM of the vehicles in v12, which I will upload now, and we can run the SQM on v13 launch.  This is just a temporary measure until I can narrow down where the conflict is.  We'll just have to save an SQM before saving and exiting the server and loading it back up when the mission restarts.

**Comment by FoxKilo** [comment]
Let me know when it's up and i'll paste the SQM when ready.

**Comment by FoxKilo** [comment]
http://pastebin.com/W5vbY8SF

Taken from V11 as V13 is currently on the server.

**Comment by FoxKilo** [comment]
http://pastebin.com/k8B4dv5h

Boxes only with fixed box locations (spawning underneath map)
