### ISSUE TITLE
Mission Saves + Continuity Information

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#47]
Each time a mission is saved please complete an SQM of the base and/or key areas you want to manually persist in case of emergency (i.e vehicle left out in the field). 

*Easy SQM tutorial= Remove all objects from Zeus, add in vehicles OR objects you want to save, check the relevant box in the options, 1km save from centre of airfield. Save vehicles and objects separately to avoid many tears.*

Note the day's losses to ensure units aren't magically/accidentally resupplied.

**Comment by coachwn** [comment]
Been doing this already to try but not having good results.

**Comment by FoxKilo** [comment]
I'm home now but have visitors so will be on soon. Can show you how we've done it on previous missions.

**Comment by coachwn** [comment]
We looking good so far?

**Comment by FoxKilo** [comment]
Server is performing ok. 2-4 people being kicked due to memory leaks. About 22 in attendance.

**Comment by FoxKilo** [comment]
I've setup RCON (hopefully) correctly so that when the server is restarted you should have "offline" access to administrate the server and give admins the option to ban, lock/unlock and restart the server without box access as per previous mission set.

**Comment by coachwn** [comment]
Thanks for the help....I owe you guys a little something extra for Christmas. We will talk about that later today when I get back.

**Comment by FoxKilo** [comment]
19th 19:16EST

Vehicles - http://pastebin.com/1dKDkkSE
Cav Boxes & staging area OBJECTS - http://pastebin.com/avFVW4Lu

All other boxes are in the original SQFs. 

Nichols to perform save later in the evening.

**Comment by jerkinmerkin** [comment]
ALiVE persistence working now, but we'll keep this going as a backup just in case.

**Comment by FoxKilo** [comment]
Couldn't log in and noticed the mission had crashed on a memory error trying to load too many memory blocks. Restarted the server and while the alive debug has shown a successful load from the DB the base is virtually reset to how the original v16 mission file is. Currently implementing my manual backups, none will be the wiser unless they read this thread ;) Merry Christmas

**Comment by FoxKilo** [comment]
P.s people reporting that base building supplies weren't available in the connex boxes, will put a limited supply so that cav can build a shelter for their boxes.

**Comment by coachwn** [comment]
Was the hangar not rebuilt on restart?

**Comment by FoxKilo** [comment]
If I remember correctly jerkin may/may not have taken a wrecking ball to it for continuity over the weekend. I told king/spanky that if they want it fixed they can include that in their next request. For now I've given them a small amount of building supplies to build a shelter.

Didn't have time to investigate the state of OPFOR on the server, seemed to persist well with AI.

**Comment by FoxKilo** [comment]
11 x GAZ 1 x in field 041061
2 x ZSU
2 x unarmed UAZ

5 x BTR
3 x BMP1
2 x BMP2
1 x T90

1 x albatross
4 x mi8
2 x mi17
3 x mi15 upk
2 x mi15 cas
2 x UAZ

as of 12/30/16.

**Comment by coachwn** [comment]
Small resupply/rebuild operation today in preparation for mission on Saturday. Fox doing a server save and reload right now. Some items not persisting correctly from resave. We have not had a mission report via the war room since last week when everything was working correctly before v16 went up.

**Comment by FoxKilo** [comment]
Persistence has been manually installed and supply requests actioned on behalf of Nichols. AI were going bat-shit crazy so i've softened them up to a level that is acceptable.

**Comment by coachwn** [comment]
Did you change that in the Vcom setting file or in the Zeus settings?

**Comment by FoxKilo** [comment]
Neither. I manually cleared and held some of the neighbouring towns to get them logged with the AI commander. Only way to guarantee results.

They just need to make a good push with combined arms to finally get through these towns. Lee/hauser need to get their battle plans compiled asap otherwise we'll still be using the same LOA I put up on day 1.

**Comment by coachwn** [comment]
Lets push the LOA out to the north side 1km further but leave the southern one in place. That way the kids can get some new ground under their pixelated feet.

**Comment by coachwn** [comment]
Rolled mission back to this past Saturday save; was on tonight in Zeus (whole different story in how that is working now) and watched several dozen enemy players spawn in the NW and SE corners of the base. It was reported that an enemy tank spawned inside the public forces hangar and was destroyed by friendly armor which resulted in the destruction of assets. So I am rolling back to see what the problem was with it.

**Comment by coachwn** [comment]
Had to replace all the vehicles...need to have someone go around and interact with all armor and SF and aircraft. Got lots of other stuff replaced. Also Cav asked for some base building supplies as well.

**Comment by FoxKilo** [comment]
https://youtu.be/UbPGK5PEcXg

Reference shilka/BTR rounds shelling the shit out of the rest of base and destroying buildings. People shouldn't be shitting where they eat.

**Comment by coachwn** [comment]
Base was already smoked by that time. Those were the last of the vehicles that had come into the base right before the server went down to 4fps and I took the whole thing down and reloaded last night.

**Comment by FoxKilo** [comment]
#Public forces

0 vehicles, 0 boxes, hangar destroyed legitimately.

#Cavalry

3 x T90
3 x BMP 1D
3 x BMP 2D
6 x BTR
~~1 x BRDM~~ Enemy asset
no boxes, hangar destroyed.

#ODA 

All vics and boxes present



#SQMs 

Base Defences http://pastebin.com/4rxfQYbu
Vehicles http://pastebin.com/SeeAizcg
Map Markers http://pastebin.com/kAK4Ay66

**Comment by FoxKilo** [comment]
Mission crashed again during major op, use of 2 air assets, big counter attack in base and lots of units seems to be the likely culprit. Noticed hyperthreading wasn't enabled on TADST, shouldn't this be on?

**Comment by coachwn** [comment]
I don't think it has been on before. I can imagine the counterattack being due to a massive ramp up in milsim action and activities. I will take a look at the hyperthread aspect tonight along with some settings adjustments for AI activities.

**Comment by coachwn** [comment]
Also might take a more in depth look at 1.2.7 for the server.

**Comment by FoxKilo** [comment]
SAF Boxes: http://pastebin.com/QRdBbk7J
SOF Boxes: http://pastebin.com/cABEVu4V
CAV Boxes: http://pastebin.com/FTt9sNUS
INF  Boxes: http://pastebin.com/85gQg4zK

For easier replacement...

Since the 2 server crashes fixed minor issues/bugs, manually reinstalled persistence again. Current situation is that Nichols recent opord will be guaranteed available to carry out as per known progress.

**Comment by coachwn** [comment]
Removing base defenses from airfield due to nothing spawning in the area other than civilians. Also adjusted cleared area down to Balota to try and kick start user activity.

**Comment by coachwn** [comment]
I used those yesterday/last night and they bugged the server for a good 3-4 minutes. Also there were no special mags or other items per what is supposed to be in the boxes for various units.

**Comment by coachwn** [comment]
Going forward we need to code boxes specifically instead of building them via editor.

**Comment by coachwn** [comment]
@FoxKilo Can you attempt to get a solid save of the areas today please? I attempted it last night and the saves were fine for the most part but the boats and the Marine base went to crap in a hurry. Things exploded and went haywire when Bayley attempted to drop in the code I saved. Also include the VCP near Kotomo if possible.
