### ISSUE TITLE
Performance monitor; RPT spam

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#48]
https://github.com/ALiVEOS/ALiVE.OS/issues/114

RPT is 500MB within 15 hours of launch due to a syntax error within the performance monitor for Alive. Quick fix is to turn it off as it renders the RPT almost unreadable. Source fix is to find the expression within the sys_perf module and fix the array/close out the expression.

2016/10/21, 19:15:35 Error in expression <(count _customCode > 0) && (diag_tickTime >= _c>
2016/10/21, 19:15:35 Error position: <_customCode > 0) && (diag_tickTime >= _c>
2016/10/21, 19:15:35 Error Undefined variable in expression: _customcode

**Comment by jerkinmerkin** [comment]
Disabled perf monitoring.
