### ISSUE TITLE
Total numbers of vehicles and airframes available for resupply to all units?

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#49]
Just wondering since I am getting resupply requests from them for things that have been destroyed in the first few days. For instance they have lost all their SU-25 due to "pilot error" and all their Mi-35's are gone as well.

**Comment by jerkinmerkin** [comment]
Server restarted, proper number of vehicles down.  Enemy areas cleared... although ALiVE keeps tasking other groups to counterattack everytime I kill them lol.  We just gotta keep up on them I guess

**Comment by coachwn** [comment]
I am Ok with the alive tasking since that is what it is going to do. Thanks for taking care of that.
