### ISSUE TITLE
Address medical settings

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#5]
Most are good,

Surgical/PAKs turn off one-time use.
SOF need ability of doctors.

**Comment by jerkinmerkin** [comment]
All of SOF?  They're all medics... the SOF medics are doctors...

**Comment by FoxKilo** [comment]
Issue was that during testing only the team medic could full heal the rest of the team and no-one else could. And that all surgical kits? but definitely Personal aid kits are on one-time use setting. Pretty much the whole team should be able to do everything to everyone.

**Comment by jerkinmerkin** [comment]
So why bother having medics if SOF can just do everything?  Every mission I've been a part of all of SOF could stitch but only medics can full heal.

**Comment by FoxKilo** [comment]
See lim/yak for the full 411 but from what i've experienced our field medicine is fine where we can all stitch and stabilise ourselves and survive. Just seems to be this issue of A) getting full heals when the medic isn't on and B) who heals the medic when he can't heal himself?

Up to you what settings you choose but that's what brass are asking fo'.

**Comment by coachwn** [comment]
Gonna play devils advocate here but from my perspective if SF all have medical full heal ability why shouldn't the rest of the community?

**Comment by FoxKilo** [comment]
Talked with Lim/Yak. Concensus is that while specific members have specific MOS they all cross train to fill and understand each other's roles hence why we all have access to the same gear. In the last couple of missions the medical settings were unified throughout the unit so they're wondering why it's now changing. Now 90% of all that means is that yes we can already do most of what we need out in the field except the last phase which is full heal hitpoints, repair broken legs etc. 

Previous issues remain intact i.e who heals the medic if you turn this off? who heals the pubbie medic and so forth. Other alternative is to make a doctor AI at the main field hospital and have him heal the medic

**Comment by jerkinmerkin** [comment]
Could I have it backwards?  Is it everyone can full heal (at medic tents) and only medics can stitch?  Still, If we go by the logic of who heals the medics, then every player should be able to full heal, not just SOF.

**Comment by jerkinmerkin** [comment]
And I know for a fact that SOF did not have 100% of the same abilities as the medics.  There is some difference.  My missions did not feature what Yak and slim claim, unless someone changed the last one in my absence.

**Comment by jerkinmerkin** [comment]
And I recall for a fact that this was agreed upon by all 3 of us at the time.

**Comment by coachwn** [comment]
Yeah I don't remember everyone being able to full heal when I was playing in SF on Reshmaan. If we needed a medic then someone switched into the slot on the team. We have done it both ways before and I think Scotty had it with full ability but honestly if we are playing as CDF then that type of force in real life does not have a fully capable medic in every slot on the team. 

As for the other suggestion you just brought up I like the idea of an AI doctor (trigger) for full heals IF and only IF you bring the patient in stable. If you have not completed all the basic stabilization then the AI should not be able to bring back to full health automatically.

**Comment by FoxKilo** [comment]
Keep the full heal setting as is, don't put in the AI.

Figure out what you want to do with stitch kits/PAKs as usually this is not on one-time use. Once that's done this issue can be closed.

**Comment by jerkinmerkin** [comment]
Fixed,
