### ISSUE TITLE
Medic's backpack full

### ISSUE THREAD

**Issue by dragonlife284** [Spearhead-Gaming-Milsim/Queens-Stallions#51]
The medic's backpack, atleast for cavalry's medic, has about 4 times as many supplies in it than normal and makes it difficult to properly gear because of how long it takes to empty

**Comment by coachwn** [comment]
Dragonlife also found that AT infantry is spawning with extra RPG items over the normal loadout.

**Comment by FoxKilo** [comment]
Fixed.
