### ISSUE TITLE
Repo files not matching server

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#6]
Specifically who put the @ace_compats folder into the repo? There are items in that folder which are going server side and therefore do not need to be downloaded by anyone NOT testing the mission. This is going to create a bigger issue when the mission goes live.

In short do not adjust repo's without checking it through with mission maker and follow up with Mission JC.

**Comment by FoxKilo** [comment]
@ace_compat still in repo after being removed. Query does this need to stay in (no current errors) or be ripped out.

**Comment by coachwn** [comment]
I will have to take it out again...I hope it does not have another entry that is set up in another file.

**Comment by coachwn** [comment]
Pulling it out of repo again right now.

**Comment by jerkinmerkin** [comment]
Wtf why does this keep happening

**Comment by coachwn** [comment]
It's become an issue within the last few months with A3Sync.
