### ISSUE TITLE
Reduce VCOM AI call radius

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#8]
reduce VCOM AI call radius

**Comment by coachwn** [comment]
Changed Vcom_AI to distance of 750 from 1200. This should reduce the number of units that are daisy chained to each other for warning and assistance.

**Comment by jerkinmerkin** [comment]
Call radius seems good to me, however VCOM artillery seems pretty OP / dumb.  Will remove.

**Comment by jerkinmerkin** [comment]
Like worse than FFE lol.

**Comment by jerkinmerkin** [comment]
At least FFE had functioning spotters.

**Comment by coachwn** [comment]
Looking at vcom for more information about artillery functions and if we can just turn it off. Would like to see if there is a way to make it a little less perfect. The fire fight tactics they use are better than anything else we have ever used.

**Comment by coachwn** [comment]
Does any of the AI use UAV's?

> _Weapon Utilization 

Want the AI to use those gosh darn static bags on their backs? What about using those big ol’ dang UAV bags? 
Well now they will! 
Expect AI to deploy static weapon bags in combat, use them to suppress/cover and then pack back up to move up. 
Also expect them to use UAV’s to locate you and share that information with everyone else!_

**Comment by coachwn** [comment]
Got this information for the reduction of arty accuracy in Vcom.

https://dl.dropboxusercontent.com/u/38334795/AIFOLDER/Arty2.png

**Comment by coachwn** [comment]
OK got this from Genesis (vcom maker) off a PM from him to me on the BI forums.
http://pastebin.com/rWQFniTA

**Comment by jerkinmerkin** [comment]
Interesting.  Let's toy around with it

**Comment by coachwn** [comment]
Call radius seems good. I think we can close that part but I want to toy with arty function for another day before we zip it up completely.
