### ISSUE TITLE
Does the CDF really need a UAV?

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Queens-Stallions#9]
Raven backpack changes back to OCP after picking it up.

**Comment by FoxKilo** [comment]
Was interested on learning how you changed this but couldn't remember which section of the file you changed. rhsusf_c_uav and rhsusf_uav both call each other.

I can read 90% of one file with notepad++ but not the other.

**Comment by jerkinmerkin** [comment]
Fixed!
